version: 2.1

executors:
  node/default:
    docker:
      - image: circleci/node:18.18-browsers # Update to Node.js 18.18 or higher

jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts

  test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress tests
          command: npx cypress run

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-node
      - test:
          requires:
            - build-node