version: 2.1

orbs:
  node: circleci/node@5
  cypress: cypress-io/cypress@3.3.1

jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  run-cypress-tests:
    executor: cypress/default
    steps:
      - checkout
      - cypress/install
      - run:
          name: Run Cypress tests
          command: |
            $(npm bin)/cypress run --project cypress/e2e/ # Adjust this command according to your project setup

workflows:
  build:
    jobs:
      - build-node
      - run-cypress-tests:
          requires:
            - build-node
